### ISSUE TITLE
[YOM-431] need some one to help with the force

### ISSUE THREAD

**Issue by HananoshikaYomaru** [HananoshikaYomaru/obsidian-3d-graph#18]
<img width="345" alt="CleanShot 2023-10-13 at 16 53 58@2x" src="https://github.com/HananoshikaYomaru/obsidian-3d-graph/assets/43137033/77df8e95-e3a5-4e53-94dc-765142d9a2c7">

These four force is difficult to work with. 

<sub>[YOM-431](https://linear.app/yomaru/issue/YOM-431/need-some-one-to-help-with-the-force)</sub>

**Comment by HananoshikaYomaru** [comment]
this is done

**Comment by huachuman** [comment]
I don't see forces options. Is this just not included yet in stable release?

**Comment by HananoshikaYomaru** [comment]
I didn't create the whole force options. The only force option is the node repulsion.
