### ISSUE TITLE
[YOM-445]   Add background layer, so it's visually easier to navigate the 3D graph

### ISSUE THREAD

**Issue by ReaderGuy42** [HananoshikaYomaru/obsidian-3d-graph#20]
**Is your feature request related to a problem? Please describe.**
No problem, but it would be easier to navigate if there was a visual way to discern how far you've moved, e.g. something like this:
![image](https://github.com/AlexW00/obsidian-3d-graph/assets/71895400/eb662c18-f09c-4640-9e25-2739f146d79d)

Except with the 3D graph you'd be inside the globe

Thanks :)

<sub>[YOM-445](https://linear.app/yomaru/issue/YOM-445/add-background-layer-so-its-visually-easier-to-navigate-the-3d-graph)</sub>

**Comment by HananoshikaYomaru** [comment]
Thanks for opening up this feature request. This is definitely a good idea. The first priority of the plugin is to make its functionality comparable to their original graph view plugin first so that people will feel like using it. Then I will look at some good to have features.

**Comment by HananoshikaYomaru** [comment]
this is not planned for now. I will close this. I saw you also open a PR in 3d force graph, hopefully this will get a response.
