### ISSUE TITLE
Styling for 3D graph

### ISSUE THREAD

**Issue by visua1hue** [HananoshikaYomaru/obsidian-3d-graph#41]
**Is your feature request related to a problem? Please describe.**
Nodes are black in dark mode.

**Describe the solution you'd like**
Add css classes / variables to target all styles. Make them available via documentation to theme devs.

**Additional context**
Default graph could be a good source for possible CSS variables

**Comment by visua1hue** [comment]
Can add screenshots if needed

**Comment by HananoshikaYomaru** [comment]
Hi, default node color are controlled by the a css variable `--text-muted` and some theme might change this to black. I think you are right that I need to put this in the customization documentation.

**Comment by visua1hue** [comment]
I would suggest to change that variable. Because --text-muted is used quite often in themes.

Maybe another color picker or a dedicated CSS variables for this plugin.

**Comment by HananoshikaYomaru** [comment]
this is done in 1.1.5. Stay tuned to my new youtube video

**Comment by visua1hue** [comment]
Seen it - good job!
