### ISSUE TITLE
[YOM-487] fail to create group, group input is missing 

### ISSUE THREAD

**Issue by HananoshikaYomaru** [HananoshikaYomaru/obsidian-3d-graph#49]
> original from https://www.reddit.com/r/ObsidianMD/comments/17j2lac/comment/k6z4fpw/?utm_source=share&utm_medium=web2x&context=3

https://imgur.com/a/cWDqFkj

<sub>[YOM-487](https://linear.app/yomaru/issue/YOM-487/fail-to-create-group-group-input-is-missing)</sub>

**Comment by DanielWalker1** [comment]
![Image 30 10 2023 at 10 19 AM](https://github.com/HananoshikaYomaru/obsidian-3d-graph/assets/108221764/9f9e364d-0b03-4b62-9550-9cacd25d7756)

So now, for some reason, the names of the files in the graph became unreadable. No idea what happened. I opened obsidian in the morning, and just saw it.

**Comment by DanielWalker1** [comment]
Also, here is the recoding on the missing Groups tab, I have sent in on reddit before but will send it here too

https://github.com/HananoshikaYomaru/obsidian-3d-graph/assets/108221764/0e6312ef-ea88-484e-96cd-e096ab65ea8a

**Comment by HananoshikaYomaru** [comment]
> ![Image 30 10 2023 at 10 19 AM](https://user-images.githubusercontent.com/108221764/278999672-9f9e364d-0b03-4b62-9550-9cacd25d7756.jpeg)
> 
> So now, for some reason, the names of the files in the graph became unreadable. No idea what happened. I opened obsidian in the morning, and just saw it.

@DanielWalker1 first of all, thx for trying the graph.  They are seperate issue. The default node color is controlled by css. You can check the README. The label text default color can also be changed by css

<img width="811" alt="CleanShot 2023-10-30 at 10 02 08@2x" src="https://github.com/HananoshikaYomaru/obsidian-3d-graph/assets/43137033/661958af-4a75-435c-bbbe-f3e2bf583e0c">

```css
.graph-3d-view .node-label {
  color: #00ff00;
}
```

so basically if there is probably related to the default color (although I am not sure why because I have no such problem), you can use css to fix it.

**Comment by DanielWalker1** [comment]
So I have corrected the colour with the css, and now, magically, the groups appeared and are working.

How, I have no idea but it works 
![Image 30 10 2023 at 7 00 PM](https://github.com/HananoshikaYomaru/obsidian-3d-graph/assets/108221764/896af36f-eb10-404e-aa12-f8d11aabaf8b)

**Comment by HananoshikaYomaru** [comment]
I don't know too. But glad you make it work 😁. Hope you enjoy the plugin. Now I will close this issue.
