### ISSUE TITLE
Link Thickness Not Working

### ISSUE THREAD

**Issue by DanielWalker1** [HananoshikaYomaru/obsidian-3d-graph#53]
**Describe the bug**
The Link Thickness in the Display settings section of the 3D Graph doesn't work, it doesn't do anything when the value is raised from 1 to any number to 3

**To Reproduce**

**Expected behavior**
I would say that the function is supposed to increase the thickness of the links between the nodes, but that doesn't happen.

**Screenshots**
Here I am proving a screen recording of the 3D Graph
![84C13C5D-3858-430E-95FE-B8E4E50A82E1_1_102_o](https://github.com/HananoshikaYomaru/obsidian-3d-graph/assets/108221764/eecdbf13-f5bb-4e24-a64b-edd239e0cd22)

**Desktop (please complete the following information):**
 - OS: MacOs Sonoma
 - Browser
 - Version 14.00

**Additional context**

**Comment by HananoshikaYomaru** [comment]
this is fixed in https://github.com/HananoshikaYomaru/obsidian-3d-graph/commit/4c5d42ff4edca3caaba00051af9b4a7f9b65b433#r135641899

**Comment by HananoshikaYomaru** [comment]
this is released in https://github.com/HananoshikaYomaru/obsidian-3d-graph/releases/tag/1.1.11
