### ISSUE TITLE
Right click to pan

### ISSUE THREAD

**Issue by huachuman** [HananoshikaYomaru/obsidian-3d-graph#54]
**Is your feature request related to a problem? Please describe.**
I often wish I didn't have to push the ctrl key to pan. 

**Describe the solution you'd like**
Holding down right click as a modifier would free up the keyboard hand to do other things.

**Describe alternatives you've considered**
Finding a way to change the code to detect right mouse down instead of ctrl, but I only have rudimentary understanding of programming.

**Additional context**

[](Planyway_Data-DO_NOT_DELETE)[](eJxljTELwjAUhP/LzWl5SYpDtmIW1yIObo8mQiE2kMSClP53H7gIwk3H993t2GKpS17hsA1QCNz49q0uAU4TKSx1TMnzG+7BqUaF2rg0MQwZ22nTaXvVJ0ck6YnoLjtxDX+A/QXmV2356eUObsfMJUw5RXHO4+RxHB+H1yt8)

**Comment by HananoshikaYomaru** [comment]
this can be made as an option in the plugin setting

**Comment by HananoshikaYomaru** [comment]
this is done

**Comment by huachuman** [comment]
This is fabulous. Thank you for your amazing work. The only thing that could possibly make this better is if right click pan worked while the left mouse button was down so one wouldn't have to release it to pan.

But whether that gets implemented or not, this is absolutely amazing.

You are by far my favorite Obsidian plugin developer. I will support you as soon as I can afford it.

**Comment by HananoshikaYomaru** [comment]
@huachuman thank you for this encouragement. It is okay I am not doing this for money (although I definitely value sponsorship because it is a confirmation). As long as you are using it, I am happy.
