### ISSUE TITLE
Groups are not visible in settings

### ISSUE THREAD

**Issue by TjeerdA** [HananoshikaYomaru/obsidian-3d-graph#55]
**Describe the bug**
In the Global 3D panel settings panel, I can click on "add Group," and the button moves down. But I cannot see anything to define the group

**To Reproduce**
In Global 3D, Settings, Add Group, ...

**Expected behavior**
It seems to work well with the local view

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS, native M1 Obsidian
 - This is in the 3D Graph New

**Additional context**
Great development thanks!

**Comment by HananoshikaYomaru** [comment]
sorry, I just saw this. Can you include a video?

**Comment by HananoshikaYomaru** [comment]
not sure if this issue is related to this: #49 . How about working in a new vault? In #49, a user report that the groups works well in new vault and in the end I have no idea how he solve that.

**Comment by TjeerdA** [comment]
Yes, you are correct. It works in another Vault. It's a pretty untractable bug/feature this way. 
Perhaps indicate this issue in the documentation

**Comment by TjeerdA** [comment]
So that you know, the issue no longer happens in my main vault. I did not even restart it. I see a beautiful, colorful 3D graph now. Thanks

**Comment by HananoshikaYomaru** [comment]
@TjeerdA glad you made it work. I will add this issue to documentation although I have no idea why it exists. 🫠
