### ISSUE TITLE
"Ctrl Left Click" to open note in new tab

### ISSUE THREAD

**Issue by Malachi-H** [HananoshikaYomaru/obsidian-3d-graph#58]
**Is your feature request related to a problem? Please describe.**
In both the native 2D graph view and the 3D graph view that this plugin provides, clicking on a node to view the content of a note replaces the graph view. The position and layout of the graph view is lost because returning to the graph view causes it to reload/restart. A simple way around this is the native functionality of  "Ctrl Left Click" opening the note in a new tab (leaving the graph view open which prevents the need to reload and loose position and layout of the graph view)

**Describe the solution you'd like**
Holding the control key on the keyboard while left clicking on a node in the 3D graph view should open the node in a new tab and switch to the newly opened tab.

The "focus on a node" function that is currently triggered by "Ctrl Left Click" could be changed to "Ctrl Right Click"

**Describe alternatives you've considered**
Persistently stored position and layout of the graph, possibly saving the graph state to a file to be reloaded when the graph view is reopened.

**Additional context**
I think this is an important feature to add because it facilitates quick exploration of node content. It also improves the parity between the native 2D and external 3D graph views.

[](Planyway_Data-DO_NOT_DELETE)[](eJxdjTELwjAUhP/Lzam8JKLwtmKWrkUc3B5NhEJsIIkFKf3vBlzE9e777jasIZc5LWCsRyh4qXL7RoMHayKFufQxOnmDHxJLUChVcm2GIWM7bTptr/rElpjoQET3thMW/wecW/sDTK9S09O1O/CGSbIfUwzNufSjw75/AIhpK30=)

**Comment by HananoshikaYomaru** [comment]
good idea, thx for opening this PR.

**Comment by HananoshikaYomaru** [comment]
I can add an option to let user customize the control left click and control right click function.

**Comment by HananoshikaYomaru** [comment]
this is done and release in https://github.com/HananoshikaYomaru/obsidian-3d-graph/releases/tag/1.1.10
